services:
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: freya-agent
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
    restart: unless-stopped
    networks:
      - freya-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: freya-web
    environment:
      - NEXT_PUBLIC_LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - agent
    restart: unless-stopped
    networks:
      - freya-network

networks:
  freya-network:
    driver: bridge
